// <auto-generated />
namespace AnonseWeb.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class editDataTypeCity2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editDataTypeCity2));
        
        string IMigrationMetadata.Id
        {
            get { return "201907041502565_editDataTypeCity2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
